default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: hermes_development

test: &test
  <<: *default
  database: hermes_test

cucumber:
  <<: *test
